name: dart_shelf
description: dart-shelf server application.
version: 1.0.0

environment:
  sdk: ">=2.18.1"

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_cors_headers: ^0.1.2
  shelf_web_socket: ^1.0.2
  shelf_static: ^1.1.1
  dart_jsonwebtoken: ^2.14.1
  mysql_client: ^0.0.27
  uuid: ^4.5.1
  mailer: ^6.2.0

dev_dependencies:
  lints: ^1.0.0
  build: ^2.3.1
  source_gen: ^1.2.3
  build_runner: ^2.0.0
